# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build and Publish SPA

on:
  release:
    types: [created]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Set VERSION Environment Variable
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
      - name: Build and Publish Shared Library - zac
        run: ./publishSharedLib.sh /zac/
      - name: Zip Shared Dist - zac
        run: |
            cd dist/app-ziti-console && zip -r ziti-console.zip *
            gh release upload ${{github.event.release.tag_name}} ziti-console.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
      - name: Upload SPA To Job - zac
        uses: actions/upload-artifact@v3
        with:
          name: ziti-console-zac-${{ env.VERSION }}.zip
          path: ziti-console-${{ env.VERSION }}.zip

      - name: Build and Publish Shared Library
        run: ./publishSharedLib.sh /
      - name: Zip Shared Dist
        run: |
          cd dist/app-ziti-console && zip -r ziti-console.zip *
          gh release upload ${{github.event.release.tag_name}} ziti-console.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
      - name: Upload SPA To Job
        uses: actions/upload-artifact@v3
        with:
          name: ziti-console-${{ env.VERSION }}.zip
          path: ziti-console-${{ env.VERSION }}.zip
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      BUILD_CONFIG: "Release"