# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build and Publish SPA

on:
  workflow_dispatch:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm install -g @angular/cli@16.0.0-next.0
      - run: ng build ziti-console-lib
      - run: ng build ziti-console
      - run: ng build ziti-console-edge
      - run: cp package-spa.json dist/app-ziti-console-edge/package.json
      - run: cd dist/app-ziti-console-edge && npm publish
      - run: cd dist/ziti-console-lib && npm publish

    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
