# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build and Publish SPA

on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Build and Publish Shared Library
        run: ./publishSharedLib.sh
      - name: Set VERSION Environment Variable
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
      - name: Upload SPA To Job
        uses: actions/upload-artifact@v3
        with:
          name: ZitiConsole-SPA-${{ env.VERSION }}
          path: "dist/app-ziti-console"
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ZitiConsole-SPA-${{ env.VERSION }}
          asset_name: ZitiConsole-SPA-${{ env.VERSION }}
          asset_content_type: application/zip

    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      BUILD_CONFIG: "Release"
