# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build and Publish SPA

on:
  release:
    types: [created]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Set VERSION Environment Variable
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
      - name: Build zip for use with controller
        run: ./build.sh /zac/
      - name: upload ziti-console.zip as SPA for use with controller
        run: |
            cd dist/app-ziti-console && zip -r ziti-console.zip *
            gh release upload ${{github.event.release.tag_name}} ziti-console.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

      - name: Check if 'publish-shared-lib' is present
        run: echo "Label 'publish-shared-lib' is present"
        if: contains(github.event.pull_request.labels.*.name, 'publish-shared-lib')

    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      BUILD_CONFIG: "Release"